#!/bin/bash
# Quick Reference for NL-MM Training

echo "════════════════════════════════════════════════════════════════"
echo "                  NL-MM TRAINING QUICK REFERENCE"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📦 INSTALLATION (if needed):"
echo "   pip install tokenizers pillow pyyaml librosa"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🚀 QUICK START:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   ./train_nlmm.sh \\"
echo "       --config modules/nl_mm/configs/nano_8gb.yaml \\"
echo "       --epochs 50 \\"
echo "       --batch_size 16"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📊 TENSORBOARD MONITORING:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   tensorboard --logdir=results/folder_per_model/nl_mm/outputs/nlmm_flickr8k/tensorboard"
echo "   Open: http://localhost:6006"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "⚙️  CONFIGURATIONS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   nano_8gb.yaml          → 13M params, 4-6GB memory (RECOMMENDED)"
echo "   tiny_single_gpu.yaml   → 50-100M params, 8-12GB memory"
echo "   base.yaml              → 200M+ params, 16GB+ memory"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔧 COMMON OPTIONS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   --epochs 50                → Number of training epochs"
echo "   --batch_size 16            → Batch size"
echo "   --lr 1e-4                  → Learning rate override"
echo "   --accumulation_steps 4     → Gradient accumulation"
echo "   --enable_ttt               → Enable test-time training"
echo "   --no_tensorboard           → Disable TensorBoard"
echo "   --eval_every 5             → Evaluation frequency"
echo "   --save_every 10            → Checkpoint frequency"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "💡 EXAMPLES:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   Quick Test (2 epochs):"
echo "   ./train_nlmm.sh --config modules/nl_mm/configs/nano_8gb.yaml --epochs 2 --batch_size 4"
echo ""
echo "   Full Training:"
echo "   ./train_nlmm.sh --config modules/nl_mm/configs/nano_8gb.yaml --epochs 50 --batch_size 16"
echo ""
echo "   With TTT:"
echo "   ./train_nlmm.sh --enable_ttt --epochs 30 --batch_size 32"
echo ""
echo "   Low Memory:"
echo "   ./train_nlmm.sh --batch_size 4 --accumulation_steps 4"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📁 OUTPUT LOCATIONS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   Checkpoints:  results/folder_per_model/nl_mm/outputs/nlmm_flickr8k/checkpoints/"
echo "   Metrics:      results/folder_per_model/nl_mm/outputs/nlmm_flickr8k/metrics.json"
echo "   TensorBoard:  results/folder_per_model/nl_mm/outputs/nlmm_flickr8k/tensorboard/"
echo "   Plots:        results/folder_per_model/nl_mm/outputs/nlmm_flickr8k/*.png"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🆘 TROUBLESHOOTING:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   ModuleNotFoundError?"
echo "   → Use ./train_nlmm.sh (NOT direct python command)"
echo ""
echo "   Out of Memory?"
echo "   → ./train_nlmm.sh --batch_size 4 --accumulation_steps 4"
echo ""
echo "   Training too slow?"
echo "   → ./train_nlmm.sh --num_workers 8"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "   Full Guide:   NLMM_TRAINING_GUIDE.md"
echo "   Fix Summary:  TRAINING_FIXES_SUMMARY.md"
echo "   Architecture: modules/nl_mm/README.md"
echo ""
echo "════════════════════════════════════════════════════════════════"

